version: "3"

services:
  mongodb:
    image: mongo:6.0.6
    environment:
      - MONGODB_DATABASE="nestjs_demo"
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express:1.0-20
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    # volumes:
    #   - mongodb-data

# volumes:
#   mongodb-data:
#     driver: local